/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the PackageLinksDownload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PackageLinksDownload{}

// PackageLinksDownload struct for PackageLinksDownload
type PackageLinksDownload struct {
	// URL to download the package
	Href *string `json:"href,omitempty"`
	// HTTP method for the download URL
	Method *string `json:"method,omitempty"`
}

// NewPackageLinksDownload instantiates a new PackageLinksDownload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageLinksDownload() *PackageLinksDownload {
	this := PackageLinksDownload{}
	return &this
}

// NewPackageLinksDownloadWithDefaults instantiates a new PackageLinksDownload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageLinksDownloadWithDefaults() *PackageLinksDownload {
	this := PackageLinksDownload{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *PackageLinksDownload) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageLinksDownload) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *PackageLinksDownload) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *PackageLinksDownload) SetHref(v string) {
	o.Href = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *PackageLinksDownload) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageLinksDownload) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *PackageLinksDownload) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *PackageLinksDownload) SetMethod(v string) {
	o.Method = &v
}

func (o PackageLinksDownload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PackageLinksDownload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	return toSerialize, nil
}

type NullablePackageLinksDownload struct {
	value *PackageLinksDownload
	isSet bool
}

func (v NullablePackageLinksDownload) Get() *PackageLinksDownload {
	return v.value
}

func (v *NullablePackageLinksDownload) Set(val *PackageLinksDownload) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageLinksDownload) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageLinksDownload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageLinksDownload(val *PackageLinksDownload) *NullablePackageLinksDownload {
	return &NullablePackageLinksDownload{value: val, isSet: true}
}

func (v NullablePackageLinksDownload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageLinksDownload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


