/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the BuildLinksPackage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildLinksPackage{}

// BuildLinksPackage struct for BuildLinksPackage
type BuildLinksPackage struct {
	// URL to the package
	Href *string `json:"href,omitempty"`
}

// NewBuildLinksPackage instantiates a new BuildLinksPackage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildLinksPackage() *BuildLinksPackage {
	this := BuildLinksPackage{}
	return &this
}

// NewBuildLinksPackageWithDefaults instantiates a new BuildLinksPackage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildLinksPackageWithDefaults() *BuildLinksPackage {
	this := BuildLinksPackage{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *BuildLinksPackage) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildLinksPackage) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *BuildLinksPackage) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *BuildLinksPackage) SetHref(v string) {
	o.Href = &v
}

func (o BuildLinksPackage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildLinksPackage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	return toSerialize, nil
}

type NullableBuildLinksPackage struct {
	value *BuildLinksPackage
	isSet bool
}

func (v NullableBuildLinksPackage) Get() *BuildLinksPackage {
	return v.value
}

func (v *NullableBuildLinksPackage) Set(val *BuildLinksPackage) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildLinksPackage) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildLinksPackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildLinksPackage(val *BuildLinksPackage) *NullableBuildLinksPackage {
	return &NullableBuildLinksPackage{value: val, isSet: true}
}

func (v NullableBuildLinksPackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildLinksPackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


