/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyOrganizationQuotaToOrganizationsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyOrganizationQuotaToOrganizationsRequest{}

// ApplyOrganizationQuotaToOrganizationsRequest struct for ApplyOrganizationQuotaToOrganizationsRequest
type ApplyOrganizationQuotaToOrganizationsRequest struct {
	// List of organization relationships to apply the quota to
	Data []ApplyOrganizationQuotaToOrganizationsRequestDataInner `json:"data"`
}

type _ApplyOrganizationQuotaToOrganizationsRequest ApplyOrganizationQuotaToOrganizationsRequest

// NewApplyOrganizationQuotaToOrganizationsRequest instantiates a new ApplyOrganizationQuotaToOrganizationsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyOrganizationQuotaToOrganizationsRequest(data []ApplyOrganizationQuotaToOrganizationsRequestDataInner) *ApplyOrganizationQuotaToOrganizationsRequest {
	this := ApplyOrganizationQuotaToOrganizationsRequest{}
	this.Data = data
	return &this
}

// NewApplyOrganizationQuotaToOrganizationsRequestWithDefaults instantiates a new ApplyOrganizationQuotaToOrganizationsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyOrganizationQuotaToOrganizationsRequestWithDefaults() *ApplyOrganizationQuotaToOrganizationsRequest {
	this := ApplyOrganizationQuotaToOrganizationsRequest{}
	return &this
}

// GetData returns the Data field value
func (o *ApplyOrganizationQuotaToOrganizationsRequest) GetData() []ApplyOrganizationQuotaToOrganizationsRequestDataInner {
	if o == nil {
		var ret []ApplyOrganizationQuotaToOrganizationsRequestDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApplyOrganizationQuotaToOrganizationsRequest) GetDataOk() ([]ApplyOrganizationQuotaToOrganizationsRequestDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApplyOrganizationQuotaToOrganizationsRequest) SetData(v []ApplyOrganizationQuotaToOrganizationsRequestDataInner) {
	o.Data = v
}

func (o ApplyOrganizationQuotaToOrganizationsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyOrganizationQuotaToOrganizationsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApplyOrganizationQuotaToOrganizationsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyOrganizationQuotaToOrganizationsRequest := _ApplyOrganizationQuotaToOrganizationsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyOrganizationQuotaToOrganizationsRequest)

	if err != nil {
		return err
	}

	*o = ApplyOrganizationQuotaToOrganizationsRequest(varApplyOrganizationQuotaToOrganizationsRequest)

	return err
}

type NullableApplyOrganizationQuotaToOrganizationsRequest struct {
	value *ApplyOrganizationQuotaToOrganizationsRequest
	isSet bool
}

func (v NullableApplyOrganizationQuotaToOrganizationsRequest) Get() *ApplyOrganizationQuotaToOrganizationsRequest {
	return v.value
}

func (v *NullableApplyOrganizationQuotaToOrganizationsRequest) Set(val *ApplyOrganizationQuotaToOrganizationsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyOrganizationQuotaToOrganizationsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyOrganizationQuotaToOrganizationsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyOrganizationQuotaToOrganizationsRequest(val *ApplyOrganizationQuotaToOrganizationsRequest) *NullableApplyOrganizationQuotaToOrganizationsRequest {
	return &NullableApplyOrganizationQuotaToOrganizationsRequest{value: val, isSet: true}
}

func (v NullableApplyOrganizationQuotaToOrganizationsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyOrganizationQuotaToOrganizationsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


