/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the AssignDefaultIsolationSegmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignDefaultIsolationSegmentRequest{}

// AssignDefaultIsolationSegmentRequest struct for AssignDefaultIsolationSegmentRequest
type AssignDefaultIsolationSegmentRequest struct {
	Data *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner `json:"data,omitempty"`
}

// NewAssignDefaultIsolationSegmentRequest instantiates a new AssignDefaultIsolationSegmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignDefaultIsolationSegmentRequest() *AssignDefaultIsolationSegmentRequest {
	this := AssignDefaultIsolationSegmentRequest{}
	return &this
}

// NewAssignDefaultIsolationSegmentRequestWithDefaults instantiates a new AssignDefaultIsolationSegmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignDefaultIsolationSegmentRequestWithDefaults() *AssignDefaultIsolationSegmentRequest {
	this := AssignDefaultIsolationSegmentRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AssignDefaultIsolationSegmentRequest) GetData() V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignDefaultIsolationSegmentRequest) GetDataOk() (*V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AssignDefaultIsolationSegmentRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner and assigns it to the Data field.
func (o *AssignDefaultIsolationSegmentRequest) SetData(v V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner) {
	o.Data = &v
}

func (o AssignDefaultIsolationSegmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignDefaultIsolationSegmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAssignDefaultIsolationSegmentRequest struct {
	value *AssignDefaultIsolationSegmentRequest
	isSet bool
}

func (v NullableAssignDefaultIsolationSegmentRequest) Get() *AssignDefaultIsolationSegmentRequest {
	return v.value
}

func (v *NullableAssignDefaultIsolationSegmentRequest) Set(val *AssignDefaultIsolationSegmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignDefaultIsolationSegmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignDefaultIsolationSegmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignDefaultIsolationSegmentRequest(val *AssignDefaultIsolationSegmentRequest) *NullableAssignDefaultIsolationSegmentRequest {
	return &NullableAssignDefaultIsolationSegmentRequest{value: val, isSet: true}
}

func (v NullableAssignDefaultIsolationSegmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignDefaultIsolationSegmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


