/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V3AppsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsPostRequest{}

// V3AppsPostRequest struct for V3AppsPostRequest
type V3AppsPostRequest struct {
	// Environment variables for the app
	EnvironmentVariables *map[string]string `json:"environment_variables,omitempty"`
	Lifecycle *V3AppsPostRequestLifecycle `json:"lifecycle,omitempty"`
	Metadata *V3AppsPostRequestMetadata `json:"metadata,omitempty"`
	// Name of the app (unique within space)
	Name string `json:"name"`
	Relationships V3AppsPostRequestRelationships `json:"relationships"`
	// Initial desired state of the app
	State *string `json:"state,omitempty"`
}

type _V3AppsPostRequest V3AppsPostRequest

// NewV3AppsPostRequest instantiates a new V3AppsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsPostRequest(name string, relationships V3AppsPostRequestRelationships) *V3AppsPostRequest {
	this := V3AppsPostRequest{}
	this.Name = name
	this.Relationships = relationships
	var state string = "STOPPED"
	this.State = &state
	return &this
}

// NewV3AppsPostRequestWithDefaults instantiates a new V3AppsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsPostRequestWithDefaults() *V3AppsPostRequest {
	this := V3AppsPostRequest{}
	var state string = "STOPPED"
	this.State = &state
	return &this
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *V3AppsPostRequest) GetEnvironmentVariables() map[string]string {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret map[string]string
		return ret
	}
	return *o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetEnvironmentVariablesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// HasEnvironmentVariables returns a boolean if a field has been set.
func (o *V3AppsPostRequest) HasEnvironmentVariables() bool {
	if o != nil && !IsNil(o.EnvironmentVariables) {
		return true
	}

	return false
}

// SetEnvironmentVariables gets a reference to the given map[string]string and assigns it to the EnvironmentVariables field.
func (o *V3AppsPostRequest) SetEnvironmentVariables(v map[string]string) {
	o.EnvironmentVariables = &v
}

// GetLifecycle returns the Lifecycle field value if set, zero value otherwise.
func (o *V3AppsPostRequest) GetLifecycle() V3AppsPostRequestLifecycle {
	if o == nil || IsNil(o.Lifecycle) {
		var ret V3AppsPostRequestLifecycle
		return ret
	}
	return *o.Lifecycle
}

// GetLifecycleOk returns a tuple with the Lifecycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetLifecycleOk() (*V3AppsPostRequestLifecycle, bool) {
	if o == nil || IsNil(o.Lifecycle) {
		return nil, false
	}
	return o.Lifecycle, true
}

// HasLifecycle returns a boolean if a field has been set.
func (o *V3AppsPostRequest) HasLifecycle() bool {
	if o != nil && !IsNil(o.Lifecycle) {
		return true
	}

	return false
}

// SetLifecycle gets a reference to the given V3AppsPostRequestLifecycle and assigns it to the Lifecycle field.
func (o *V3AppsPostRequest) SetLifecycle(v V3AppsPostRequestLifecycle) {
	o.Lifecycle = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *V3AppsPostRequest) GetMetadata() V3AppsPostRequestMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret V3AppsPostRequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetMetadataOk() (*V3AppsPostRequestMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *V3AppsPostRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V3AppsPostRequestMetadata and assigns it to the Metadata field.
func (o *V3AppsPostRequest) SetMetadata(v V3AppsPostRequestMetadata) {
	o.Metadata = &v
}

// GetName returns the Name field value
func (o *V3AppsPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V3AppsPostRequest) SetName(v string) {
	o.Name = v
}

// GetRelationships returns the Relationships field value
func (o *V3AppsPostRequest) GetRelationships() V3AppsPostRequestRelationships {
	if o == nil {
		var ret V3AppsPostRequestRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetRelationshipsOk() (*V3AppsPostRequestRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *V3AppsPostRequest) SetRelationships(v V3AppsPostRequestRelationships) {
	o.Relationships = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V3AppsPostRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsPostRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V3AppsPostRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *V3AppsPostRequest) SetState(v string) {
	o.State = &v
}

func (o V3AppsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environment_variables"] = o.EnvironmentVariables
	}
	if !IsNil(o.Lifecycle) {
		toSerialize["lifecycle"] = o.Lifecycle
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	toSerialize["relationships"] = o.Relationships
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

func (o *V3AppsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV3AppsPostRequest := _V3AppsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV3AppsPostRequest)

	if err != nil {
		return err
	}

	*o = V3AppsPostRequest(varV3AppsPostRequest)

	return err
}

type NullableV3AppsPostRequest struct {
	value *V3AppsPostRequest
	isSet bool
}

func (v NullableV3AppsPostRequest) Get() *V3AppsPostRequest {
	return v.value
}

func (v *NullableV3AppsPostRequest) Set(val *V3AppsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsPostRequest(val *V3AppsPostRequest) *NullableV3AppsPostRequest {
	return &NullableV3AppsPostRequest{value: val, isSet: true}
}

func (v NullableV3AppsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


