/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the ServiceUsageEventLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceUsageEventLinks{}

// ServiceUsageEventLinks struct for ServiceUsageEventLinks
type ServiceUsageEventLinks struct {
	Self *string `json:"self,omitempty"`
}

// NewServiceUsageEventLinks instantiates a new ServiceUsageEventLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceUsageEventLinks() *ServiceUsageEventLinks {
	this := ServiceUsageEventLinks{}
	return &this
}

// NewServiceUsageEventLinksWithDefaults instantiates a new ServiceUsageEventLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceUsageEventLinksWithDefaults() *ServiceUsageEventLinks {
	this := ServiceUsageEventLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ServiceUsageEventLinks) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceUsageEventLinks) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ServiceUsageEventLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *ServiceUsageEventLinks) SetSelf(v string) {
	o.Self = &v
}

func (o ServiceUsageEventLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceUsageEventLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableServiceUsageEventLinks struct {
	value *ServiceUsageEventLinks
	isSet bool
}

func (v NullableServiceUsageEventLinks) Get() *ServiceUsageEventLinks {
	return v.value
}

func (v *NullableServiceUsageEventLinks) Set(val *ServiceUsageEventLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceUsageEventLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceUsageEventLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceUsageEventLinks(val *ServiceUsageEventLinks) *NullableServiceUsageEventLinks {
	return &NullableServiceUsageEventLinks{value: val, isSet: true}
}

func (v NullableServiceUsageEventLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceUsageEventLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


