/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V3ServiceBrokersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3ServiceBrokersPostRequest{}

// V3ServiceBrokersPostRequest struct for V3ServiceBrokersPostRequest
type V3ServiceBrokersPostRequest struct {
	Authentication Authentication `json:"authentication"`
	Metadata *Metadata `json:"metadata,omitempty"`
	Name string `json:"name"`
	Relationships *V3ServiceBrokersPostRequestRelationships `json:"relationships,omitempty"`
	Url string `json:"url"`
}

type _V3ServiceBrokersPostRequest V3ServiceBrokersPostRequest

// NewV3ServiceBrokersPostRequest instantiates a new V3ServiceBrokersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3ServiceBrokersPostRequest(authentication Authentication, name string, url string) *V3ServiceBrokersPostRequest {
	this := V3ServiceBrokersPostRequest{}
	this.Authentication = authentication
	this.Name = name
	this.Url = url
	return &this
}

// NewV3ServiceBrokersPostRequestWithDefaults instantiates a new V3ServiceBrokersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3ServiceBrokersPostRequestWithDefaults() *V3ServiceBrokersPostRequest {
	this := V3ServiceBrokersPostRequest{}
	return &this
}

// GetAuthentication returns the Authentication field value
func (o *V3ServiceBrokersPostRequest) GetAuthentication() Authentication {
	if o == nil {
		var ret Authentication
		return ret
	}

	return o.Authentication
}

// GetAuthenticationOk returns a tuple with the Authentication field value
// and a boolean to check if the value has been set.
func (o *V3ServiceBrokersPostRequest) GetAuthenticationOk() (*Authentication, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authentication, true
}

// SetAuthentication sets field value
func (o *V3ServiceBrokersPostRequest) SetAuthentication(v Authentication) {
	o.Authentication = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *V3ServiceBrokersPostRequest) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3ServiceBrokersPostRequest) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *V3ServiceBrokersPostRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *V3ServiceBrokersPostRequest) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetName returns the Name field value
func (o *V3ServiceBrokersPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V3ServiceBrokersPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V3ServiceBrokersPostRequest) SetName(v string) {
	o.Name = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *V3ServiceBrokersPostRequest) GetRelationships() V3ServiceBrokersPostRequestRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret V3ServiceBrokersPostRequestRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3ServiceBrokersPostRequest) GetRelationshipsOk() (*V3ServiceBrokersPostRequestRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *V3ServiceBrokersPostRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given V3ServiceBrokersPostRequestRelationships and assigns it to the Relationships field.
func (o *V3ServiceBrokersPostRequest) SetRelationships(v V3ServiceBrokersPostRequestRelationships) {
	o.Relationships = &v
}

// GetUrl returns the Url field value
func (o *V3ServiceBrokersPostRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *V3ServiceBrokersPostRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *V3ServiceBrokersPostRequest) SetUrl(v string) {
	o.Url = v
}

func (o V3ServiceBrokersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3ServiceBrokersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authentication"] = o.Authentication
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *V3ServiceBrokersPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authentication",
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV3ServiceBrokersPostRequest := _V3ServiceBrokersPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV3ServiceBrokersPostRequest)

	if err != nil {
		return err
	}

	*o = V3ServiceBrokersPostRequest(varV3ServiceBrokersPostRequest)

	return err
}

type NullableV3ServiceBrokersPostRequest struct {
	value *V3ServiceBrokersPostRequest
	isSet bool
}

func (v NullableV3ServiceBrokersPostRequest) Get() *V3ServiceBrokersPostRequest {
	return v.value
}

func (v *NullableV3ServiceBrokersPostRequest) Set(val *V3ServiceBrokersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV3ServiceBrokersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV3ServiceBrokersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3ServiceBrokersPostRequest(val *V3ServiceBrokersPostRequest) *NullableV3ServiceBrokersPostRequest {
	return &NullableV3ServiceBrokersPostRequest{value: val, isSet: true}
}

func (v NullableV3ServiceBrokersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3ServiceBrokersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


