/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the PackageDataChecksum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PackageDataChecksum{}

// PackageDataChecksum struct for PackageDataChecksum
type PackageDataChecksum struct {
	// The checksum type, for example: sha256
	Type *string `json:"type,omitempty"`
	// The checksum value; this will be populated after bits are uploaded
	Value NullableString `json:"value,omitempty"`
}

// NewPackageDataChecksum instantiates a new PackageDataChecksum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageDataChecksum() *PackageDataChecksum {
	this := PackageDataChecksum{}
	return &this
}

// NewPackageDataChecksumWithDefaults instantiates a new PackageDataChecksum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageDataChecksumWithDefaults() *PackageDataChecksum {
	this := PackageDataChecksum{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PackageDataChecksum) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageDataChecksum) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PackageDataChecksum) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PackageDataChecksum) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PackageDataChecksum) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PackageDataChecksum) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *PackageDataChecksum) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *PackageDataChecksum) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *PackageDataChecksum) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *PackageDataChecksum) UnsetValue() {
	o.Value.Unset()
}

func (o PackageDataChecksum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PackageDataChecksum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

type NullablePackageDataChecksum struct {
	value *PackageDataChecksum
	isSet bool
}

func (v NullablePackageDataChecksum) Get() *PackageDataChecksum {
	return v.value
}

func (v *NullablePackageDataChecksum) Set(val *PackageDataChecksum) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageDataChecksum) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageDataChecksum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageDataChecksum(val *PackageDataChecksum) *NullablePackageDataChecksum {
	return &NullablePackageDataChecksum{value: val, isSet: true}
}

func (v NullablePackageDataChecksum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageDataChecksum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


