/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the SpaceQuotaCreateMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceQuotaCreateMetadata{}

// SpaceQuotaCreateMetadata Additional metadata for the space quota
type SpaceQuotaCreateMetadata struct {
	// Key-value pairs for storing additional information
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Key-value pairs for organizing and filtering
	Labels *map[string]string `json:"labels,omitempty"`
}

// NewSpaceQuotaCreateMetadata instantiates a new SpaceQuotaCreateMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceQuotaCreateMetadata() *SpaceQuotaCreateMetadata {
	this := SpaceQuotaCreateMetadata{}
	return &this
}

// NewSpaceQuotaCreateMetadataWithDefaults instantiates a new SpaceQuotaCreateMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceQuotaCreateMetadataWithDefaults() *SpaceQuotaCreateMetadata {
	this := SpaceQuotaCreateMetadata{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *SpaceQuotaCreateMetadata) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceQuotaCreateMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *SpaceQuotaCreateMetadata) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *SpaceQuotaCreateMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *SpaceQuotaCreateMetadata) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceQuotaCreateMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SpaceQuotaCreateMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SpaceQuotaCreateMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

func (o SpaceQuotaCreateMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceQuotaCreateMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableSpaceQuotaCreateMetadata struct {
	value *SpaceQuotaCreateMetadata
	isSet bool
}

func (v NullableSpaceQuotaCreateMetadata) Get() *SpaceQuotaCreateMetadata {
	return v.value
}

func (v *NullableSpaceQuotaCreateMetadata) Set(val *SpaceQuotaCreateMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceQuotaCreateMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceQuotaCreateMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceQuotaCreateMetadata(val *SpaceQuotaCreateMetadata) *NullableSpaceQuotaCreateMetadata {
	return &NullableSpaceQuotaCreateMetadata{value: val, isSet: true}
}

func (v NullableSpaceQuotaCreateMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceQuotaCreateMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


