/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the CreateOrganizationQuotaRequestDomains type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationQuotaRequestDomains{}

// CreateOrganizationQuotaRequestDomains struct for CreateOrganizationQuotaRequestDomains
type CreateOrganizationQuotaRequestDomains struct {
	// Total number of domains that can be scoped to an organization
	TotalDomains NullableInt32 `json:"total_domains,omitempty"`
}

// NewCreateOrganizationQuotaRequestDomains instantiates a new CreateOrganizationQuotaRequestDomains object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationQuotaRequestDomains() *CreateOrganizationQuotaRequestDomains {
	this := CreateOrganizationQuotaRequestDomains{}
	return &this
}

// NewCreateOrganizationQuotaRequestDomainsWithDefaults instantiates a new CreateOrganizationQuotaRequestDomains object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationQuotaRequestDomainsWithDefaults() *CreateOrganizationQuotaRequestDomains {
	this := CreateOrganizationQuotaRequestDomains{}
	return &this
}

// GetTotalDomains returns the TotalDomains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrganizationQuotaRequestDomains) GetTotalDomains() int32 {
	if o == nil || IsNil(o.TotalDomains.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalDomains.Get()
}

// GetTotalDomainsOk returns a tuple with the TotalDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrganizationQuotaRequestDomains) GetTotalDomainsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalDomains.Get(), o.TotalDomains.IsSet()
}

// HasTotalDomains returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequestDomains) HasTotalDomains() bool {
	if o != nil && o.TotalDomains.IsSet() {
		return true
	}

	return false
}

// SetTotalDomains gets a reference to the given NullableInt32 and assigns it to the TotalDomains field.
func (o *CreateOrganizationQuotaRequestDomains) SetTotalDomains(v int32) {
	o.TotalDomains.Set(&v)
}
// SetTotalDomainsNil sets the value for TotalDomains to be an explicit nil
func (o *CreateOrganizationQuotaRequestDomains) SetTotalDomainsNil() {
	o.TotalDomains.Set(nil)
}

// UnsetTotalDomains ensures that no value is present for TotalDomains, not even an explicit nil
func (o *CreateOrganizationQuotaRequestDomains) UnsetTotalDomains() {
	o.TotalDomains.Unset()
}

func (o CreateOrganizationQuotaRequestDomains) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationQuotaRequestDomains) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TotalDomains.IsSet() {
		toSerialize["total_domains"] = o.TotalDomains.Get()
	}
	return toSerialize, nil
}

type NullableCreateOrganizationQuotaRequestDomains struct {
	value *CreateOrganizationQuotaRequestDomains
	isSet bool
}

func (v NullableCreateOrganizationQuotaRequestDomains) Get() *CreateOrganizationQuotaRequestDomains {
	return v.value
}

func (v *NullableCreateOrganizationQuotaRequestDomains) Set(val *CreateOrganizationQuotaRequestDomains) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationQuotaRequestDomains) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationQuotaRequestDomains) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationQuotaRequestDomains(val *CreateOrganizationQuotaRequestDomains) *NullableCreateOrganizationQuotaRequestDomains {
	return &NullableCreateOrganizationQuotaRequestDomains{value: val, isSet: true}
}

func (v NullableCreateOrganizationQuotaRequestDomains) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationQuotaRequestDomains) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


