/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3AppsGuidEnvGet200ResponseSystemEnvJson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsGuidEnvGet200ResponseSystemEnvJson{}

// V3AppsGuidEnvGet200ResponseSystemEnvJson struct for V3AppsGuidEnvGet200ResponseSystemEnvJson
type V3AppsGuidEnvGet200ResponseSystemEnvJson struct {
	VCAP_SERVICES *map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner `json:"VCAP_SERVICES,omitempty"`
}

// NewV3AppsGuidEnvGet200ResponseSystemEnvJson instantiates a new V3AppsGuidEnvGet200ResponseSystemEnvJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsGuidEnvGet200ResponseSystemEnvJson() *V3AppsGuidEnvGet200ResponseSystemEnvJson {
	this := V3AppsGuidEnvGet200ResponseSystemEnvJson{}
	return &this
}

// NewV3AppsGuidEnvGet200ResponseSystemEnvJsonWithDefaults instantiates a new V3AppsGuidEnvGet200ResponseSystemEnvJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsGuidEnvGet200ResponseSystemEnvJsonWithDefaults() *V3AppsGuidEnvGet200ResponseSystemEnvJson {
	this := V3AppsGuidEnvGet200ResponseSystemEnvJson{}
	return &this
}

// GetVCAP_SERVICES returns the VCAP_SERVICES field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseSystemEnvJson) GetVCAP_SERVICES() map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner {
	if o == nil || IsNil(o.VCAP_SERVICES) {
		var ret map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner
		return ret
	}
	return *o.VCAP_SERVICES
}

// GetVCAP_SERVICESOk returns a tuple with the VCAP_SERVICES field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseSystemEnvJson) GetVCAP_SERVICESOk() (*map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner, bool) {
	if o == nil || IsNil(o.VCAP_SERVICES) {
		return nil, false
	}
	return o.VCAP_SERVICES, true
}

// HasVCAP_SERVICES returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseSystemEnvJson) HasVCAP_SERVICES() bool {
	if o != nil && !IsNil(o.VCAP_SERVICES) {
		return true
	}

	return false
}

// SetVCAP_SERVICES gets a reference to the given map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner and assigns it to the VCAP_SERVICES field.
func (o *V3AppsGuidEnvGet200ResponseSystemEnvJson) SetVCAP_SERVICES(v map[string][]V3AppsGuidEnvGet200ResponseSystemEnvJsonVCAPSERVICESValueInner) {
	o.VCAP_SERVICES = &v
}

func (o V3AppsGuidEnvGet200ResponseSystemEnvJson) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsGuidEnvGet200ResponseSystemEnvJson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VCAP_SERVICES) {
		toSerialize["VCAP_SERVICES"] = o.VCAP_SERVICES
	}
	return toSerialize, nil
}

type NullableV3AppsGuidEnvGet200ResponseSystemEnvJson struct {
	value *V3AppsGuidEnvGet200ResponseSystemEnvJson
	isSet bool
}

func (v NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) Get() *V3AppsGuidEnvGet200ResponseSystemEnvJson {
	return v.value
}

func (v *NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) Set(val *V3AppsGuidEnvGet200ResponseSystemEnvJson) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsGuidEnvGet200ResponseSystemEnvJson(val *V3AppsGuidEnvGet200ResponseSystemEnvJson) *NullableV3AppsGuidEnvGet200ResponseSystemEnvJson {
	return &NullableV3AppsGuidEnvGet200ResponseSystemEnvJson{value: val, isSet: true}
}

func (v NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsGuidEnvGet200ResponseSystemEnvJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


