/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response{}

// V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response struct for V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response
type V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response struct {
	Data []V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner `json:"data,omitempty"`
	Links *V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks `json:"links,omitempty"`
}

// NewV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response instantiates a new V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response() *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response {
	this := V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response{}
	return &this
}

// NewV3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseWithDefaults instantiates a new V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseWithDefaults() *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response {
	this := V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) GetData() []V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) GetDataOk() ([]V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner and assigns it to the Data field.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) SetData(v []V3IsolationSegmentsGuidRelationshipsOrganizationsGet200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) GetLinks() V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) GetLinksOk() (*V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks and assigns it to the Links field.
func (o *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) SetLinks(v V3AppsGuidRelationshipsCurrentDropletGet200ResponseLinks) {
	o.Links = &v
}

func (o V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response struct {
	value *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response
	isSet bool
}

func (v NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) Get() *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response {
	return v.value
}

func (v *NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) Set(val *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response(val *V3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) *NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response {
	return &NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response{value: val, isSet: true}
}

func (v NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3IsolationSegmentsGuidRelationshipsOrganizationsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


