/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V3DeploymentsPostRequestRelationshipsApp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3DeploymentsPostRequestRelationshipsApp{}

// V3DeploymentsPostRequestRelationshipsApp struct for V3DeploymentsPostRequestRelationshipsApp
type V3DeploymentsPostRequestRelationshipsApp struct {
	Data V3DeploymentsPostRequestRelationshipsAppData `json:"data"`
}

type _V3DeploymentsPostRequestRelationshipsApp V3DeploymentsPostRequestRelationshipsApp

// NewV3DeploymentsPostRequestRelationshipsApp instantiates a new V3DeploymentsPostRequestRelationshipsApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3DeploymentsPostRequestRelationshipsApp(data V3DeploymentsPostRequestRelationshipsAppData) *V3DeploymentsPostRequestRelationshipsApp {
	this := V3DeploymentsPostRequestRelationshipsApp{}
	this.Data = data
	return &this
}

// NewV3DeploymentsPostRequestRelationshipsAppWithDefaults instantiates a new V3DeploymentsPostRequestRelationshipsApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3DeploymentsPostRequestRelationshipsAppWithDefaults() *V3DeploymentsPostRequestRelationshipsApp {
	this := V3DeploymentsPostRequestRelationshipsApp{}
	return &this
}

// GetData returns the Data field value
func (o *V3DeploymentsPostRequestRelationshipsApp) GetData() V3DeploymentsPostRequestRelationshipsAppData {
	if o == nil {
		var ret V3DeploymentsPostRequestRelationshipsAppData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V3DeploymentsPostRequestRelationshipsApp) GetDataOk() (*V3DeploymentsPostRequestRelationshipsAppData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V3DeploymentsPostRequestRelationshipsApp) SetData(v V3DeploymentsPostRequestRelationshipsAppData) {
	o.Data = v
}

func (o V3DeploymentsPostRequestRelationshipsApp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3DeploymentsPostRequestRelationshipsApp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *V3DeploymentsPostRequestRelationshipsApp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV3DeploymentsPostRequestRelationshipsApp := _V3DeploymentsPostRequestRelationshipsApp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV3DeploymentsPostRequestRelationshipsApp)

	if err != nil {
		return err
	}

	*o = V3DeploymentsPostRequestRelationshipsApp(varV3DeploymentsPostRequestRelationshipsApp)

	return err
}

type NullableV3DeploymentsPostRequestRelationshipsApp struct {
	value *V3DeploymentsPostRequestRelationshipsApp
	isSet bool
}

func (v NullableV3DeploymentsPostRequestRelationshipsApp) Get() *V3DeploymentsPostRequestRelationshipsApp {
	return v.value
}

func (v *NullableV3DeploymentsPostRequestRelationshipsApp) Set(val *V3DeploymentsPostRequestRelationshipsApp) {
	v.value = val
	v.isSet = true
}

func (v NullableV3DeploymentsPostRequestRelationshipsApp) IsSet() bool {
	return v.isSet
}

func (v *NullableV3DeploymentsPostRequestRelationshipsApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3DeploymentsPostRequestRelationshipsApp(val *V3DeploymentsPostRequestRelationshipsApp) *NullableV3DeploymentsPostRequestRelationshipsApp {
	return &NullableV3DeploymentsPostRequestRelationshipsApp{value: val, isSet: true}
}

func (v NullableV3DeploymentsPostRequestRelationshipsApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3DeploymentsPostRequestRelationshipsApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


