/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the ServicePlanRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicePlanRelationships{}

// ServicePlanRelationships struct for ServicePlanRelationships
type ServicePlanRelationships struct {
	ServiceOffering *AssignDefaultIsolationSegmentRequest `json:"service_offering,omitempty"`
}

// NewServicePlanRelationships instantiates a new ServicePlanRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePlanRelationships() *ServicePlanRelationships {
	this := ServicePlanRelationships{}
	return &this
}

// NewServicePlanRelationshipsWithDefaults instantiates a new ServicePlanRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePlanRelationshipsWithDefaults() *ServicePlanRelationships {
	this := ServicePlanRelationships{}
	return &this
}

// GetServiceOffering returns the ServiceOffering field value if set, zero value otherwise.
func (o *ServicePlanRelationships) GetServiceOffering() AssignDefaultIsolationSegmentRequest {
	if o == nil || IsNil(o.ServiceOffering) {
		var ret AssignDefaultIsolationSegmentRequest
		return ret
	}
	return *o.ServiceOffering
}

// GetServiceOfferingOk returns a tuple with the ServiceOffering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicePlanRelationships) GetServiceOfferingOk() (*AssignDefaultIsolationSegmentRequest, bool) {
	if o == nil || IsNil(o.ServiceOffering) {
		return nil, false
	}
	return o.ServiceOffering, true
}

// HasServiceOffering returns a boolean if a field has been set.
func (o *ServicePlanRelationships) HasServiceOffering() bool {
	if o != nil && !IsNil(o.ServiceOffering) {
		return true
	}

	return false
}

// SetServiceOffering gets a reference to the given AssignDefaultIsolationSegmentRequest and assigns it to the ServiceOffering field.
func (o *ServicePlanRelationships) SetServiceOffering(v AssignDefaultIsolationSegmentRequest) {
	o.ServiceOffering = &v
}

func (o ServicePlanRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicePlanRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceOffering) {
		toSerialize["service_offering"] = o.ServiceOffering
	}
	return toSerialize, nil
}

type NullableServicePlanRelationships struct {
	value *ServicePlanRelationships
	isSet bool
}

func (v NullableServicePlanRelationships) Get() *ServicePlanRelationships {
	return v.value
}

func (v *NullableServicePlanRelationships) Set(val *ServicePlanRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePlanRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePlanRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePlanRelationships(val *ServicePlanRelationships) *NullableServicePlanRelationships {
	return &NullableServicePlanRelationships{value: val, isSet: true}
}

func (v NullableServicePlanRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePlanRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


