/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationQuotaRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationQuotaRelationships{}

// OrganizationQuotaRelationships struct for OrganizationQuotaRelationships
type OrganizationQuotaRelationships struct {
	Organizations OrganizationQuotaRelationshipsOrganizations `json:"organizations"`
}

type _OrganizationQuotaRelationships OrganizationQuotaRelationships

// NewOrganizationQuotaRelationships instantiates a new OrganizationQuotaRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationQuotaRelationships(organizations OrganizationQuotaRelationshipsOrganizations) *OrganizationQuotaRelationships {
	this := OrganizationQuotaRelationships{}
	this.Organizations = organizations
	return &this
}

// NewOrganizationQuotaRelationshipsWithDefaults instantiates a new OrganizationQuotaRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationQuotaRelationshipsWithDefaults() *OrganizationQuotaRelationships {
	this := OrganizationQuotaRelationships{}
	return &this
}

// GetOrganizations returns the Organizations field value
func (o *OrganizationQuotaRelationships) GetOrganizations() OrganizationQuotaRelationshipsOrganizations {
	if o == nil {
		var ret OrganizationQuotaRelationshipsOrganizations
		return ret
	}

	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value
// and a boolean to check if the value has been set.
func (o *OrganizationQuotaRelationships) GetOrganizationsOk() (*OrganizationQuotaRelationshipsOrganizations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organizations, true
}

// SetOrganizations sets field value
func (o *OrganizationQuotaRelationships) SetOrganizations(v OrganizationQuotaRelationshipsOrganizations) {
	o.Organizations = v
}

func (o OrganizationQuotaRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationQuotaRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizations"] = o.Organizations
	return toSerialize, nil
}

func (o *OrganizationQuotaRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationQuotaRelationships := _OrganizationQuotaRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationQuotaRelationships)

	if err != nil {
		return err
	}

	*o = OrganizationQuotaRelationships(varOrganizationQuotaRelationships)

	return err
}

type NullableOrganizationQuotaRelationships struct {
	value *OrganizationQuotaRelationships
	isSet bool
}

func (v NullableOrganizationQuotaRelationships) Get() *OrganizationQuotaRelationships {
	return v.value
}

func (v *NullableOrganizationQuotaRelationships) Set(val *OrganizationQuotaRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationQuotaRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationQuotaRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationQuotaRelationships(val *OrganizationQuotaRelationships) *NullableOrganizationQuotaRelationships {
	return &NullableOrganizationQuotaRelationships{value: val, isSet: true}
}

func (v NullableOrganizationQuotaRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationQuotaRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


