/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the Get200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Get200Response{}

// Get200Response struct for Get200Response
type Get200Response struct {
	Links *Get200ResponseLinks `json:"links,omitempty"`
}

// NewGet200Response instantiates a new Get200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGet200Response() *Get200Response {
	this := Get200Response{}
	return &this
}

// NewGet200ResponseWithDefaults instantiates a new Get200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGet200ResponseWithDefaults() *Get200Response {
	this := Get200Response{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *Get200Response) GetLinks() Get200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret Get200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Get200Response) GetLinksOk() (*Get200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *Get200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Get200ResponseLinks and assigns it to the Links field.
func (o *Get200Response) SetLinks(v Get200ResponseLinks) {
	o.Links = &v
}

func (o Get200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Get200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGet200Response struct {
	value *Get200Response
	isSet bool
}

func (v NullableGet200Response) Get() *Get200Response {
	return v.value
}

func (v *NullableGet200Response) Set(val *Get200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGet200Response(val *Get200Response) *NullableGet200Response {
	return &NullableGet200Response{value: val, isSet: true}
}

func (v NullableGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


