/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3AppsGuidDropletsCurrentGet200ResponseChecksum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsGuidDropletsCurrentGet200ResponseChecksum{}

// V3AppsGuidDropletsCurrentGet200ResponseChecksum struct for V3AppsGuidDropletsCurrentGet200ResponseChecksum
type V3AppsGuidDropletsCurrentGet200ResponseChecksum struct {
	Type *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewV3AppsGuidDropletsCurrentGet200ResponseChecksum instantiates a new V3AppsGuidDropletsCurrentGet200ResponseChecksum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsGuidDropletsCurrentGet200ResponseChecksum() *V3AppsGuidDropletsCurrentGet200ResponseChecksum {
	this := V3AppsGuidDropletsCurrentGet200ResponseChecksum{}
	return &this
}

// NewV3AppsGuidDropletsCurrentGet200ResponseChecksumWithDefaults instantiates a new V3AppsGuidDropletsCurrentGet200ResponseChecksum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsGuidDropletsCurrentGet200ResponseChecksumWithDefaults() *V3AppsGuidDropletsCurrentGet200ResponseChecksum {
	this := V3AppsGuidDropletsCurrentGet200ResponseChecksum{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *V3AppsGuidDropletsCurrentGet200ResponseChecksum) SetValue(v string) {
	o.Value = &v
}

func (o V3AppsGuidDropletsCurrentGet200ResponseChecksum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsGuidDropletsCurrentGet200ResponseChecksum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum struct {
	value *V3AppsGuidDropletsCurrentGet200ResponseChecksum
	isSet bool
}

func (v NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) Get() *V3AppsGuidDropletsCurrentGet200ResponseChecksum {
	return v.value
}

func (v *NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) Set(val *V3AppsGuidDropletsCurrentGet200ResponseChecksum) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsGuidDropletsCurrentGet200ResponseChecksum(val *V3AppsGuidDropletsCurrentGet200ResponseChecksum) *NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum {
	return &NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum{value: val, isSet: true}
}

func (v NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsGuidDropletsCurrentGet200ResponseChecksum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


