/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the SpaceQuotaMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceQuotaMetadata{}

// SpaceQuotaMetadata Additional metadata for the space quota
type SpaceQuotaMetadata struct {
	// Key-value pairs for storing additional information
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Key-value pairs for organizing and filtering
	Labels *map[string]string `json:"labels,omitempty"`
}

// NewSpaceQuotaMetadata instantiates a new SpaceQuotaMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceQuotaMetadata() *SpaceQuotaMetadata {
	this := SpaceQuotaMetadata{}
	return &this
}

// NewSpaceQuotaMetadataWithDefaults instantiates a new SpaceQuotaMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceQuotaMetadataWithDefaults() *SpaceQuotaMetadata {
	this := SpaceQuotaMetadata{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *SpaceQuotaMetadata) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceQuotaMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *SpaceQuotaMetadata) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *SpaceQuotaMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *SpaceQuotaMetadata) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceQuotaMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SpaceQuotaMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SpaceQuotaMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

func (o SpaceQuotaMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceQuotaMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableSpaceQuotaMetadata struct {
	value *SpaceQuotaMetadata
	isSet bool
}

func (v NullableSpaceQuotaMetadata) Get() *SpaceQuotaMetadata {
	return v.value
}

func (v *NullableSpaceQuotaMetadata) Set(val *SpaceQuotaMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceQuotaMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceQuotaMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceQuotaMetadata(val *SpaceQuotaMetadata) *NullableSpaceQuotaMetadata {
	return &NullableSpaceQuotaMetadata{value: val, isSet: true}
}

func (v NullableSpaceQuotaMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceQuotaMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


