/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the CreateAppRequestMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAppRequestMetadata{}

// CreateAppRequestMetadata struct for CreateAppRequestMetadata
type CreateAppRequestMetadata struct {
	// Key-value pairs for storing metadata
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Key-value pairs for labeling and filtering
	Labels *map[string]string `json:"labels,omitempty"`
}

// NewCreateAppRequestMetadata instantiates a new CreateAppRequestMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppRequestMetadata() *CreateAppRequestMetadata {
	this := CreateAppRequestMetadata{}
	return &this
}

// NewCreateAppRequestMetadataWithDefaults instantiates a new CreateAppRequestMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppRequestMetadataWithDefaults() *CreateAppRequestMetadata {
	this := CreateAppRequestMetadata{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *CreateAppRequestMetadata) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppRequestMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *CreateAppRequestMetadata) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *CreateAppRequestMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateAppRequestMetadata) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppRequestMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateAppRequestMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateAppRequestMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

func (o CreateAppRequestMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAppRequestMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableCreateAppRequestMetadata struct {
	value *CreateAppRequestMetadata
	isSet bool
}

func (v NullableCreateAppRequestMetadata) Get() *CreateAppRequestMetadata {
	return v.value
}

func (v *NullableCreateAppRequestMetadata) Set(val *CreateAppRequestMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppRequestMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppRequestMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppRequestMetadata(val *CreateAppRequestMetadata) *NullableCreateAppRequestMetadata {
	return &NullableCreateAppRequestMetadata{value: val, isSet: true}
}

func (v NullableCreateAppRequestMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppRequestMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


