/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the ManagedServiceInstanceUpdateRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedServiceInstanceUpdateRelationships{}

// ManagedServiceInstanceUpdateRelationships struct for ManagedServiceInstanceUpdateRelationships
type ManagedServiceInstanceUpdateRelationships struct {
	ServicePlan *ToOneRelationship `json:"service_plan,omitempty"`
}

// NewManagedServiceInstanceUpdateRelationships instantiates a new ManagedServiceInstanceUpdateRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedServiceInstanceUpdateRelationships() *ManagedServiceInstanceUpdateRelationships {
	this := ManagedServiceInstanceUpdateRelationships{}
	return &this
}

// NewManagedServiceInstanceUpdateRelationshipsWithDefaults instantiates a new ManagedServiceInstanceUpdateRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedServiceInstanceUpdateRelationshipsWithDefaults() *ManagedServiceInstanceUpdateRelationships {
	this := ManagedServiceInstanceUpdateRelationships{}
	return &this
}

// GetServicePlan returns the ServicePlan field value if set, zero value otherwise.
func (o *ManagedServiceInstanceUpdateRelationships) GetServicePlan() ToOneRelationship {
	if o == nil || IsNil(o.ServicePlan) {
		var ret ToOneRelationship
		return ret
	}
	return *o.ServicePlan
}

// GetServicePlanOk returns a tuple with the ServicePlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedServiceInstanceUpdateRelationships) GetServicePlanOk() (*ToOneRelationship, bool) {
	if o == nil || IsNil(o.ServicePlan) {
		return nil, false
	}
	return o.ServicePlan, true
}

// HasServicePlan returns a boolean if a field has been set.
func (o *ManagedServiceInstanceUpdateRelationships) HasServicePlan() bool {
	if o != nil && !IsNil(o.ServicePlan) {
		return true
	}

	return false
}

// SetServicePlan gets a reference to the given ToOneRelationship and assigns it to the ServicePlan field.
func (o *ManagedServiceInstanceUpdateRelationships) SetServicePlan(v ToOneRelationship) {
	o.ServicePlan = &v
}

func (o ManagedServiceInstanceUpdateRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedServiceInstanceUpdateRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServicePlan) {
		toSerialize["service_plan"] = o.ServicePlan
	}
	return toSerialize, nil
}

type NullableManagedServiceInstanceUpdateRelationships struct {
	value *ManagedServiceInstanceUpdateRelationships
	isSet bool
}

func (v NullableManagedServiceInstanceUpdateRelationships) Get() *ManagedServiceInstanceUpdateRelationships {
	return v.value
}

func (v *NullableManagedServiceInstanceUpdateRelationships) Set(val *ManagedServiceInstanceUpdateRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedServiceInstanceUpdateRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedServiceInstanceUpdateRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedServiceInstanceUpdateRelationships(val *ManagedServiceInstanceUpdateRelationships) *NullableManagedServiceInstanceUpdateRelationships {
	return &NullableManagedServiceInstanceUpdateRelationships{value: val, isSet: true}
}

func (v NullableManagedServiceInstanceUpdateRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedServiceInstanceUpdateRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


