/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppLifecycle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppLifecycle{}

// AppLifecycle struct for AppLifecycle
type AppLifecycle struct {
	Data AppLifecycleData `json:"data"`
	// Lifecycle type
	Type string `json:"type"`
}

type _AppLifecycle AppLifecycle

// NewAppLifecycle instantiates a new AppLifecycle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppLifecycle(data AppLifecycleData, type_ string) *AppLifecycle {
	this := AppLifecycle{}
	this.Data = data
	this.Type = type_
	return &this
}

// NewAppLifecycleWithDefaults instantiates a new AppLifecycle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppLifecycleWithDefaults() *AppLifecycle {
	this := AppLifecycle{}
	return &this
}

// GetData returns the Data field value
func (o *AppLifecycle) GetData() AppLifecycleData {
	if o == nil {
		var ret AppLifecycleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppLifecycle) GetDataOk() (*AppLifecycleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppLifecycle) SetData(v AppLifecycleData) {
	o.Data = v
}

// GetType returns the Type field value
func (o *AppLifecycle) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppLifecycle) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppLifecycle) SetType(v string) {
	o.Type = v
}

func (o AppLifecycle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppLifecycle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AppLifecycle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppLifecycle := _AppLifecycle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppLifecycle)

	if err != nil {
		return err
	}

	*o = AppLifecycle(varAppLifecycle)

	return err
}

type NullableAppLifecycle struct {
	value *AppLifecycle
	isSet bool
}

func (v NullableAppLifecycle) Get() *AppLifecycle {
	return v.value
}

func (v *NullableAppLifecycle) Set(val *AppLifecycle) {
	v.value = val
	v.isSet = true
}

func (v NullableAppLifecycle) IsSet() bool {
	return v.isSet
}

func (v *NullableAppLifecycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppLifecycle(val *AppLifecycle) *NullableAppLifecycle {
	return &NullableAppLifecycle{value: val, isSet: true}
}

func (v NullableAppLifecycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppLifecycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


