/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the ErrorTestModeInfoSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorTestModeInfoSource{}

// ErrorTestModeInfoSource struct for ErrorTestModeInfoSource
type ErrorTestModeInfoSource struct {
	// Query parameter that caused the error
	Parameter *string `json:"parameter,omitempty"`
	// JSON pointer to the source of the error
	Pointer *string `json:"pointer,omitempty"`
}

// NewErrorTestModeInfoSource instantiates a new ErrorTestModeInfoSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorTestModeInfoSource() *ErrorTestModeInfoSource {
	this := ErrorTestModeInfoSource{}
	return &this
}

// NewErrorTestModeInfoSourceWithDefaults instantiates a new ErrorTestModeInfoSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorTestModeInfoSourceWithDefaults() *ErrorTestModeInfoSource {
	this := ErrorTestModeInfoSource{}
	return &this
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *ErrorTestModeInfoSource) GetParameter() string {
	if o == nil || IsNil(o.Parameter) {
		var ret string
		return ret
	}
	return *o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTestModeInfoSource) GetParameterOk() (*string, bool) {
	if o == nil || IsNil(o.Parameter) {
		return nil, false
	}
	return o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *ErrorTestModeInfoSource) HasParameter() bool {
	if o != nil && !IsNil(o.Parameter) {
		return true
	}

	return false
}

// SetParameter gets a reference to the given string and assigns it to the Parameter field.
func (o *ErrorTestModeInfoSource) SetParameter(v string) {
	o.Parameter = &v
}

// GetPointer returns the Pointer field value if set, zero value otherwise.
func (o *ErrorTestModeInfoSource) GetPointer() string {
	if o == nil || IsNil(o.Pointer) {
		var ret string
		return ret
	}
	return *o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTestModeInfoSource) GetPointerOk() (*string, bool) {
	if o == nil || IsNil(o.Pointer) {
		return nil, false
	}
	return o.Pointer, true
}

// HasPointer returns a boolean if a field has been set.
func (o *ErrorTestModeInfoSource) HasPointer() bool {
	if o != nil && !IsNil(o.Pointer) {
		return true
	}

	return false
}

// SetPointer gets a reference to the given string and assigns it to the Pointer field.
func (o *ErrorTestModeInfoSource) SetPointer(v string) {
	o.Pointer = &v
}

func (o ErrorTestModeInfoSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorTestModeInfoSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parameter) {
		toSerialize["parameter"] = o.Parameter
	}
	if !IsNil(o.Pointer) {
		toSerialize["pointer"] = o.Pointer
	}
	return toSerialize, nil
}

type NullableErrorTestModeInfoSource struct {
	value *ErrorTestModeInfoSource
	isSet bool
}

func (v NullableErrorTestModeInfoSource) Get() *ErrorTestModeInfoSource {
	return v.value
}

func (v *NullableErrorTestModeInfoSource) Set(val *ErrorTestModeInfoSource) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorTestModeInfoSource) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorTestModeInfoSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorTestModeInfoSource(val *ErrorTestModeInfoSource) *NullableErrorTestModeInfoSource {
	return &NullableErrorTestModeInfoSource{value: val, isSet: true}
}

func (v NullableErrorTestModeInfoSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorTestModeInfoSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


