/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the CreateOrganizationQuotaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationQuotaRequest{}

// CreateOrganizationQuotaRequest struct for CreateOrganizationQuotaRequest
type CreateOrganizationQuotaRequest struct {
	Apps *CreateOrganizationQuotaRequestApps `json:"apps,omitempty"`
	Domains *CreateOrganizationQuotaRequestDomains `json:"domains,omitempty"`
	// Name of the quota
	Name *string `json:"name,omitempty"`
	Relationships *CreateOrganizationQuotaRequestRelationships `json:"relationships,omitempty"`
	Routes *CreateOrganizationQuotaRequestRoutes `json:"routes,omitempty"`
	Services *CreateOrganizationQuotaRequestServices `json:"services,omitempty"`
}

// NewCreateOrganizationQuotaRequest instantiates a new CreateOrganizationQuotaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationQuotaRequest() *CreateOrganizationQuotaRequest {
	this := CreateOrganizationQuotaRequest{}
	return &this
}

// NewCreateOrganizationQuotaRequestWithDefaults instantiates a new CreateOrganizationQuotaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationQuotaRequestWithDefaults() *CreateOrganizationQuotaRequest {
	this := CreateOrganizationQuotaRequest{}
	return &this
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetApps() CreateOrganizationQuotaRequestApps {
	if o == nil || IsNil(o.Apps) {
		var ret CreateOrganizationQuotaRequestApps
		return ret
	}
	return *o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetAppsOk() (*CreateOrganizationQuotaRequestApps, bool) {
	if o == nil || IsNil(o.Apps) {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasApps() bool {
	if o != nil && !IsNil(o.Apps) {
		return true
	}

	return false
}

// SetApps gets a reference to the given CreateOrganizationQuotaRequestApps and assigns it to the Apps field.
func (o *CreateOrganizationQuotaRequest) SetApps(v CreateOrganizationQuotaRequestApps) {
	o.Apps = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetDomains() CreateOrganizationQuotaRequestDomains {
	if o == nil || IsNil(o.Domains) {
		var ret CreateOrganizationQuotaRequestDomains
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetDomainsOk() (*CreateOrganizationQuotaRequestDomains, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given CreateOrganizationQuotaRequestDomains and assigns it to the Domains field.
func (o *CreateOrganizationQuotaRequest) SetDomains(v CreateOrganizationQuotaRequestDomains) {
	o.Domains = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateOrganizationQuotaRequest) SetName(v string) {
	o.Name = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetRelationships() CreateOrganizationQuotaRequestRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret CreateOrganizationQuotaRequestRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetRelationshipsOk() (*CreateOrganizationQuotaRequestRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given CreateOrganizationQuotaRequestRelationships and assigns it to the Relationships field.
func (o *CreateOrganizationQuotaRequest) SetRelationships(v CreateOrganizationQuotaRequestRelationships) {
	o.Relationships = &v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetRoutes() CreateOrganizationQuotaRequestRoutes {
	if o == nil || IsNil(o.Routes) {
		var ret CreateOrganizationQuotaRequestRoutes
		return ret
	}
	return *o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetRoutesOk() (*CreateOrganizationQuotaRequestRoutes, bool) {
	if o == nil || IsNil(o.Routes) {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasRoutes() bool {
	if o != nil && !IsNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given CreateOrganizationQuotaRequestRoutes and assigns it to the Routes field.
func (o *CreateOrganizationQuotaRequest) SetRoutes(v CreateOrganizationQuotaRequestRoutes) {
	o.Routes = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *CreateOrganizationQuotaRequest) GetServices() CreateOrganizationQuotaRequestServices {
	if o == nil || IsNil(o.Services) {
		var ret CreateOrganizationQuotaRequestServices
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuotaRequest) GetServicesOk() (*CreateOrganizationQuotaRequestServices, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *CreateOrganizationQuotaRequest) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given CreateOrganizationQuotaRequestServices and assigns it to the Services field.
func (o *CreateOrganizationQuotaRequest) SetServices(v CreateOrganizationQuotaRequestServices) {
	o.Services = &v
}

func (o CreateOrganizationQuotaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationQuotaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	if !IsNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableCreateOrganizationQuotaRequest struct {
	value *CreateOrganizationQuotaRequest
	isSet bool
}

func (v NullableCreateOrganizationQuotaRequest) Get() *CreateOrganizationQuotaRequest {
	return v.value
}

func (v *NullableCreateOrganizationQuotaRequest) Set(val *CreateOrganizationQuotaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationQuotaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationQuotaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationQuotaRequest(val *CreateOrganizationQuotaRequest) *NullableCreateOrganizationQuotaRequest {
	return &NullableCreateOrganizationQuotaRequest{value: val, isSet: true}
}

func (v NullableCreateOrganizationQuotaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationQuotaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


