/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecurityGroupLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityGroupLinksSelf{}

// SecurityGroupLinksSelf struct for SecurityGroupLinksSelf
type SecurityGroupLinksSelf struct {
	Href string `json:"href"`
}

type _SecurityGroupLinksSelf SecurityGroupLinksSelf

// NewSecurityGroupLinksSelf instantiates a new SecurityGroupLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityGroupLinksSelf(href string) *SecurityGroupLinksSelf {
	this := SecurityGroupLinksSelf{}
	this.Href = href
	return &this
}

// NewSecurityGroupLinksSelfWithDefaults instantiates a new SecurityGroupLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityGroupLinksSelfWithDefaults() *SecurityGroupLinksSelf {
	this := SecurityGroupLinksSelf{}
	return &this
}

// GetHref returns the Href field value
func (o *SecurityGroupLinksSelf) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *SecurityGroupLinksSelf) SetHref(v string) {
	o.Href = v
}

func (o SecurityGroupLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityGroupLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["href"] = o.Href
	return toSerialize, nil
}

func (o *SecurityGroupLinksSelf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"href",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecurityGroupLinksSelf := _SecurityGroupLinksSelf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecurityGroupLinksSelf)

	if err != nil {
		return err
	}

	*o = SecurityGroupLinksSelf(varSecurityGroupLinksSelf)

	return err
}

type NullableSecurityGroupLinksSelf struct {
	value *SecurityGroupLinksSelf
	isSet bool
}

func (v NullableSecurityGroupLinksSelf) Get() *SecurityGroupLinksSelf {
	return v.value
}

func (v *NullableSecurityGroupLinksSelf) Set(val *SecurityGroupLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityGroupLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityGroupLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityGroupLinksSelf(val *SecurityGroupLinksSelf) *NullableSecurityGroupLinksSelf {
	return &NullableSecurityGroupLinksSelf{value: val, isSet: true}
}

func (v NullableSecurityGroupLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityGroupLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


