/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION{}

// V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION struct for V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION
type V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION struct {
	ApplicationName *string `json:"application_name,omitempty"`
	ApplicationUris []string `json:"application_uris,omitempty"`
	Limits *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits `json:"limits,omitempty"`
	Name *string `json:"name,omitempty"`
	SpaceId *string `json:"space_id,omitempty"`
	SpaceName *string `json:"space_name,omitempty"`
	Uris []string `json:"uris,omitempty"`
	Users NullableString `json:"users,omitempty"`
}

// NewV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION instantiates a new V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION() *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION {
	this := V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION{}
	return &this
}

// NewV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONWithDefaults instantiates a new V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONWithDefaults() *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION {
	this := V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION{}
	return &this
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetApplicationUris returns the ApplicationUris field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetApplicationUris() []string {
	if o == nil || IsNil(o.ApplicationUris) {
		var ret []string
		return ret
	}
	return o.ApplicationUris
}

// GetApplicationUrisOk returns a tuple with the ApplicationUris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetApplicationUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.ApplicationUris) {
		return nil, false
	}
	return o.ApplicationUris, true
}

// HasApplicationUris returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasApplicationUris() bool {
	if o != nil && !IsNil(o.ApplicationUris) {
		return true
	}

	return false
}

// SetApplicationUris gets a reference to the given []string and assigns it to the ApplicationUris field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetApplicationUris(v []string) {
	o.ApplicationUris = v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetLimits() V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits {
	if o == nil || IsNil(o.Limits) {
		var ret V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetLimitsOk() (*V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits and assigns it to the Limits field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetLimits(v V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATIONLimits) {
	o.Limits = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetName(v string) {
	o.Name = &v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetSpaceName returns the SpaceName field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetSpaceName() string {
	if o == nil || IsNil(o.SpaceName) {
		var ret string
		return ret
	}
	return *o.SpaceName
}

// GetSpaceNameOk returns a tuple with the SpaceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetSpaceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceName) {
		return nil, false
	}
	return o.SpaceName, true
}

// HasSpaceName returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasSpaceName() bool {
	if o != nil && !IsNil(o.SpaceName) {
		return true
	}

	return false
}

// SetSpaceName gets a reference to the given string and assigns it to the SpaceName field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetSpaceName(v string) {
	o.SpaceName = &v
}

// GetUris returns the Uris field value if set, zero value otherwise.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetUris() []string {
	if o == nil || IsNil(o.Uris) {
		var ret []string
		return ret
	}
	return o.Uris
}

// GetUrisOk returns a tuple with the Uris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.Uris) {
		return nil, false
	}
	return o.Uris, true
}

// HasUris returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasUris() bool {
	if o != nil && !IsNil(o.Uris) {
		return true
	}

	return false
}

// SetUris gets a reference to the given []string and assigns it to the Uris field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetUris(v []string) {
	o.Uris = v
}

// GetUsers returns the Users field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetUsers() string {
	if o == nil || IsNil(o.Users.Get()) {
		var ret string
		return ret
	}
	return *o.Users.Get()
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) GetUsersOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users.Get(), o.Users.IsSet()
}

// HasUsers returns a boolean if a field has been set.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) HasUsers() bool {
	if o != nil && o.Users.IsSet() {
		return true
	}

	return false
}

// SetUsers gets a reference to the given NullableString and assigns it to the Users field.
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetUsers(v string) {
	o.Users.Set(&v)
}
// SetUsersNil sets the value for Users to be an explicit nil
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) SetUsersNil() {
	o.Users.Set(nil)
}

// UnsetUsers ensures that no value is present for Users, not even an explicit nil
func (o *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) UnsetUsers() {
	o.Users.Unset()
}

func (o V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationName) {
		toSerialize["application_name"] = o.ApplicationName
	}
	if !IsNil(o.ApplicationUris) {
		toSerialize["application_uris"] = o.ApplicationUris
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SpaceId) {
		toSerialize["space_id"] = o.SpaceId
	}
	if !IsNil(o.SpaceName) {
		toSerialize["space_name"] = o.SpaceName
	}
	if !IsNil(o.Uris) {
		toSerialize["uris"] = o.Uris
	}
	if o.Users.IsSet() {
		toSerialize["users"] = o.Users.Get()
	}
	return toSerialize, nil
}

type NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION struct {
	value *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION
	isSet bool
}

func (v NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) Get() *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION {
	return v.value
}

func (v *NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) Set(val *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION(val *V3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) *NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION {
	return &NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION{value: val, isSet: true}
}

func (v NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsGuidEnvGet200ResponseApplicationEnvJsonVCAPAPPLICATION) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


