/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3DropletsPostRequestRelationshipsApp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3DropletsPostRequestRelationshipsApp{}

// V3DropletsPostRequestRelationshipsApp struct for V3DropletsPostRequestRelationshipsApp
type V3DropletsPostRequestRelationshipsApp struct {
	Data *V3DropletsPostRequestRelationshipsAppData `json:"data,omitempty"`
}

// NewV3DropletsPostRequestRelationshipsApp instantiates a new V3DropletsPostRequestRelationshipsApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3DropletsPostRequestRelationshipsApp() *V3DropletsPostRequestRelationshipsApp {
	this := V3DropletsPostRequestRelationshipsApp{}
	return &this
}

// NewV3DropletsPostRequestRelationshipsAppWithDefaults instantiates a new V3DropletsPostRequestRelationshipsApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3DropletsPostRequestRelationshipsAppWithDefaults() *V3DropletsPostRequestRelationshipsApp {
	this := V3DropletsPostRequestRelationshipsApp{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V3DropletsPostRequestRelationshipsApp) GetData() V3DropletsPostRequestRelationshipsAppData {
	if o == nil || IsNil(o.Data) {
		var ret V3DropletsPostRequestRelationshipsAppData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3DropletsPostRequestRelationshipsApp) GetDataOk() (*V3DropletsPostRequestRelationshipsAppData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V3DropletsPostRequestRelationshipsApp) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given V3DropletsPostRequestRelationshipsAppData and assigns it to the Data field.
func (o *V3DropletsPostRequestRelationshipsApp) SetData(v V3DropletsPostRequestRelationshipsAppData) {
	o.Data = &v
}

func (o V3DropletsPostRequestRelationshipsApp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3DropletsPostRequestRelationshipsApp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableV3DropletsPostRequestRelationshipsApp struct {
	value *V3DropletsPostRequestRelationshipsApp
	isSet bool
}

func (v NullableV3DropletsPostRequestRelationshipsApp) Get() *V3DropletsPostRequestRelationshipsApp {
	return v.value
}

func (v *NullableV3DropletsPostRequestRelationshipsApp) Set(val *V3DropletsPostRequestRelationshipsApp) {
	v.value = val
	v.isSet = true
}

func (v NullableV3DropletsPostRequestRelationshipsApp) IsSet() bool {
	return v.isSet
}

func (v *NullableV3DropletsPostRequestRelationshipsApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3DropletsPostRequestRelationshipsApp(val *V3DropletsPostRequestRelationshipsApp) *NullableV3DropletsPostRequestRelationshipsApp {
	return &NullableV3DropletsPostRequestRelationshipsApp{value: val, isSet: true}
}

func (v NullableV3DropletsPostRequestRelationshipsApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3DropletsPostRequestRelationshipsApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


