/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the V3AppsGuidTasksPostRequestTemplateProcess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsGuidTasksPostRequestTemplateProcess{}

// V3AppsGuidTasksPostRequestTemplateProcess struct for V3AppsGuidTasksPostRequestTemplateProcess
type V3AppsGuidTasksPostRequestTemplateProcess struct {
	// The guid of the process that will be used as a template
	Guid *string `json:"guid,omitempty"`
}

// NewV3AppsGuidTasksPostRequestTemplateProcess instantiates a new V3AppsGuidTasksPostRequestTemplateProcess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsGuidTasksPostRequestTemplateProcess() *V3AppsGuidTasksPostRequestTemplateProcess {
	this := V3AppsGuidTasksPostRequestTemplateProcess{}
	return &this
}

// NewV3AppsGuidTasksPostRequestTemplateProcessWithDefaults instantiates a new V3AppsGuidTasksPostRequestTemplateProcess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsGuidTasksPostRequestTemplateProcessWithDefaults() *V3AppsGuidTasksPostRequestTemplateProcess {
	this := V3AppsGuidTasksPostRequestTemplateProcess{}
	return &this
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *V3AppsGuidTasksPostRequestTemplateProcess) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidTasksPostRequestTemplateProcess) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *V3AppsGuidTasksPostRequestTemplateProcess) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *V3AppsGuidTasksPostRequestTemplateProcess) SetGuid(v string) {
	o.Guid = &v
}

func (o V3AppsGuidTasksPostRequestTemplateProcess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsGuidTasksPostRequestTemplateProcess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	return toSerialize, nil
}

type NullableV3AppsGuidTasksPostRequestTemplateProcess struct {
	value *V3AppsGuidTasksPostRequestTemplateProcess
	isSet bool
}

func (v NullableV3AppsGuidTasksPostRequestTemplateProcess) Get() *V3AppsGuidTasksPostRequestTemplateProcess {
	return v.value
}

func (v *NullableV3AppsGuidTasksPostRequestTemplateProcess) Set(val *V3AppsGuidTasksPostRequestTemplateProcess) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsGuidTasksPostRequestTemplateProcess) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsGuidTasksPostRequestTemplateProcess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsGuidTasksPostRequestTemplateProcess(val *V3AppsGuidTasksPostRequestTemplateProcess) *NullableV3AppsGuidTasksPostRequestTemplateProcess {
	return &NullableV3AppsGuidTasksPostRequestTemplateProcess{value: val, isSet: true}
}

func (v NullableV3AppsGuidTasksPostRequestTemplateProcess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsGuidTasksPostRequestTemplateProcess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


