/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationQuotaApps type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationQuotaApps{}

// OrganizationQuotaApps Application resource limits
type OrganizationQuotaApps struct {
	// Log rate limit per second (null = unlimited)
	LogRateLimitInBytesPerSecond NullableInt32 `json:"log_rate_limit_in_bytes_per_second"`
	// Maximum tasks per app (null = unlimited)
	PerAppTasks NullableInt32 `json:"per_app_tasks"`
	// Memory limit per app process (null = unlimited)
	PerProcessMemoryInMb NullableInt32 `json:"per_process_memory_in_mb"`
	// Total app instances allowed (null = unlimited)
	TotalInstances NullableInt32 `json:"total_instances"`
	// Total memory limit for all apps (null = unlimited)
	TotalMemoryInMb NullableInt32 `json:"total_memory_in_mb"`
}

type _OrganizationQuotaApps OrganizationQuotaApps

// NewOrganizationQuotaApps instantiates a new OrganizationQuotaApps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationQuotaApps(logRateLimitInBytesPerSecond NullableInt32, perAppTasks NullableInt32, perProcessMemoryInMb NullableInt32, totalInstances NullableInt32, totalMemoryInMb NullableInt32) *OrganizationQuotaApps {
	this := OrganizationQuotaApps{}
	this.LogRateLimitInBytesPerSecond = logRateLimitInBytesPerSecond
	this.PerAppTasks = perAppTasks
	this.PerProcessMemoryInMb = perProcessMemoryInMb
	this.TotalInstances = totalInstances
	this.TotalMemoryInMb = totalMemoryInMb
	return &this
}

// NewOrganizationQuotaAppsWithDefaults instantiates a new OrganizationQuotaApps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationQuotaAppsWithDefaults() *OrganizationQuotaApps {
	this := OrganizationQuotaApps{}
	return &this
}

// GetLogRateLimitInBytesPerSecond returns the LogRateLimitInBytesPerSecond field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OrganizationQuotaApps) GetLogRateLimitInBytesPerSecond() int32 {
	if o == nil || o.LogRateLimitInBytesPerSecond.Get() == nil {
		var ret int32
		return ret
	}

	return *o.LogRateLimitInBytesPerSecond.Get()
}

// GetLogRateLimitInBytesPerSecondOk returns a tuple with the LogRateLimitInBytesPerSecond field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationQuotaApps) GetLogRateLimitInBytesPerSecondOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogRateLimitInBytesPerSecond.Get(), o.LogRateLimitInBytesPerSecond.IsSet()
}

// SetLogRateLimitInBytesPerSecond sets field value
func (o *OrganizationQuotaApps) SetLogRateLimitInBytesPerSecond(v int32) {
	o.LogRateLimitInBytesPerSecond.Set(&v)
}

// GetPerAppTasks returns the PerAppTasks field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OrganizationQuotaApps) GetPerAppTasks() int32 {
	if o == nil || o.PerAppTasks.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PerAppTasks.Get()
}

// GetPerAppTasksOk returns a tuple with the PerAppTasks field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationQuotaApps) GetPerAppTasksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PerAppTasks.Get(), o.PerAppTasks.IsSet()
}

// SetPerAppTasks sets field value
func (o *OrganizationQuotaApps) SetPerAppTasks(v int32) {
	o.PerAppTasks.Set(&v)
}

// GetPerProcessMemoryInMb returns the PerProcessMemoryInMb field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OrganizationQuotaApps) GetPerProcessMemoryInMb() int32 {
	if o == nil || o.PerProcessMemoryInMb.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PerProcessMemoryInMb.Get()
}

// GetPerProcessMemoryInMbOk returns a tuple with the PerProcessMemoryInMb field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationQuotaApps) GetPerProcessMemoryInMbOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PerProcessMemoryInMb.Get(), o.PerProcessMemoryInMb.IsSet()
}

// SetPerProcessMemoryInMb sets field value
func (o *OrganizationQuotaApps) SetPerProcessMemoryInMb(v int32) {
	o.PerProcessMemoryInMb.Set(&v)
}

// GetTotalInstances returns the TotalInstances field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OrganizationQuotaApps) GetTotalInstances() int32 {
	if o == nil || o.TotalInstances.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TotalInstances.Get()
}

// GetTotalInstancesOk returns a tuple with the TotalInstances field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationQuotaApps) GetTotalInstancesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalInstances.Get(), o.TotalInstances.IsSet()
}

// SetTotalInstances sets field value
func (o *OrganizationQuotaApps) SetTotalInstances(v int32) {
	o.TotalInstances.Set(&v)
}

// GetTotalMemoryInMb returns the TotalMemoryInMb field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OrganizationQuotaApps) GetTotalMemoryInMb() int32 {
	if o == nil || o.TotalMemoryInMb.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TotalMemoryInMb.Get()
}

// GetTotalMemoryInMbOk returns a tuple with the TotalMemoryInMb field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationQuotaApps) GetTotalMemoryInMbOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalMemoryInMb.Get(), o.TotalMemoryInMb.IsSet()
}

// SetTotalMemoryInMb sets field value
func (o *OrganizationQuotaApps) SetTotalMemoryInMb(v int32) {
	o.TotalMemoryInMb.Set(&v)
}

func (o OrganizationQuotaApps) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationQuotaApps) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["log_rate_limit_in_bytes_per_second"] = o.LogRateLimitInBytesPerSecond.Get()
	toSerialize["per_app_tasks"] = o.PerAppTasks.Get()
	toSerialize["per_process_memory_in_mb"] = o.PerProcessMemoryInMb.Get()
	toSerialize["total_instances"] = o.TotalInstances.Get()
	toSerialize["total_memory_in_mb"] = o.TotalMemoryInMb.Get()
	return toSerialize, nil
}

func (o *OrganizationQuotaApps) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"log_rate_limit_in_bytes_per_second",
		"per_app_tasks",
		"per_process_memory_in_mb",
		"total_instances",
		"total_memory_in_mb",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationQuotaApps := _OrganizationQuotaApps{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationQuotaApps)

	if err != nil {
		return err
	}

	*o = OrganizationQuotaApps(varOrganizationQuotaApps)

	return err
}

type NullableOrganizationQuotaApps struct {
	value *OrganizationQuotaApps
	isSet bool
}

func (v NullableOrganizationQuotaApps) Get() *OrganizationQuotaApps {
	return v.value
}

func (v *NullableOrganizationQuotaApps) Set(val *OrganizationQuotaApps) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationQuotaApps) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationQuotaApps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationQuotaApps(val *OrganizationQuotaApps) *NullableOrganizationQuotaApps {
	return &NullableOrganizationQuotaApps{value: val, isSet: true}
}

func (v NullableOrganizationQuotaApps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationQuotaApps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


