/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
)

// checks if the SpaceQuotaUpdateServices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceQuotaUpdateServices{}

// SpaceQuotaUpdateServices Service resource limits
type SpaceQuotaUpdateServices struct {
	// Whether paid services are allowed
	PaidServicesAllowed *bool `json:"paid_services_allowed,omitempty"`
	// Total service instances allowed (null = unlimited)
	TotalServiceInstances NullableInt32 `json:"total_service_instances,omitempty"`
	// Total service keys allowed (null = unlimited)
	TotalServiceKeys NullableInt32 `json:"total_service_keys,omitempty"`
}

// NewSpaceQuotaUpdateServices instantiates a new SpaceQuotaUpdateServices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceQuotaUpdateServices() *SpaceQuotaUpdateServices {
	this := SpaceQuotaUpdateServices{}
	return &this
}

// NewSpaceQuotaUpdateServicesWithDefaults instantiates a new SpaceQuotaUpdateServices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceQuotaUpdateServicesWithDefaults() *SpaceQuotaUpdateServices {
	this := SpaceQuotaUpdateServices{}
	return &this
}

// GetPaidServicesAllowed returns the PaidServicesAllowed field value if set, zero value otherwise.
func (o *SpaceQuotaUpdateServices) GetPaidServicesAllowed() bool {
	if o == nil || IsNil(o.PaidServicesAllowed) {
		var ret bool
		return ret
	}
	return *o.PaidServicesAllowed
}

// GetPaidServicesAllowedOk returns a tuple with the PaidServicesAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceQuotaUpdateServices) GetPaidServicesAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.PaidServicesAllowed) {
		return nil, false
	}
	return o.PaidServicesAllowed, true
}

// HasPaidServicesAllowed returns a boolean if a field has been set.
func (o *SpaceQuotaUpdateServices) HasPaidServicesAllowed() bool {
	if o != nil && !IsNil(o.PaidServicesAllowed) {
		return true
	}

	return false
}

// SetPaidServicesAllowed gets a reference to the given bool and assigns it to the PaidServicesAllowed field.
func (o *SpaceQuotaUpdateServices) SetPaidServicesAllowed(v bool) {
	o.PaidServicesAllowed = &v
}

// GetTotalServiceInstances returns the TotalServiceInstances field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpaceQuotaUpdateServices) GetTotalServiceInstances() int32 {
	if o == nil || IsNil(o.TotalServiceInstances.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalServiceInstances.Get()
}

// GetTotalServiceInstancesOk returns a tuple with the TotalServiceInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpaceQuotaUpdateServices) GetTotalServiceInstancesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalServiceInstances.Get(), o.TotalServiceInstances.IsSet()
}

// HasTotalServiceInstances returns a boolean if a field has been set.
func (o *SpaceQuotaUpdateServices) HasTotalServiceInstances() bool {
	if o != nil && o.TotalServiceInstances.IsSet() {
		return true
	}

	return false
}

// SetTotalServiceInstances gets a reference to the given NullableInt32 and assigns it to the TotalServiceInstances field.
func (o *SpaceQuotaUpdateServices) SetTotalServiceInstances(v int32) {
	o.TotalServiceInstances.Set(&v)
}
// SetTotalServiceInstancesNil sets the value for TotalServiceInstances to be an explicit nil
func (o *SpaceQuotaUpdateServices) SetTotalServiceInstancesNil() {
	o.TotalServiceInstances.Set(nil)
}

// UnsetTotalServiceInstances ensures that no value is present for TotalServiceInstances, not even an explicit nil
func (o *SpaceQuotaUpdateServices) UnsetTotalServiceInstances() {
	o.TotalServiceInstances.Unset()
}

// GetTotalServiceKeys returns the TotalServiceKeys field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpaceQuotaUpdateServices) GetTotalServiceKeys() int32 {
	if o == nil || IsNil(o.TotalServiceKeys.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalServiceKeys.Get()
}

// GetTotalServiceKeysOk returns a tuple with the TotalServiceKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpaceQuotaUpdateServices) GetTotalServiceKeysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalServiceKeys.Get(), o.TotalServiceKeys.IsSet()
}

// HasTotalServiceKeys returns a boolean if a field has been set.
func (o *SpaceQuotaUpdateServices) HasTotalServiceKeys() bool {
	if o != nil && o.TotalServiceKeys.IsSet() {
		return true
	}

	return false
}

// SetTotalServiceKeys gets a reference to the given NullableInt32 and assigns it to the TotalServiceKeys field.
func (o *SpaceQuotaUpdateServices) SetTotalServiceKeys(v int32) {
	o.TotalServiceKeys.Set(&v)
}
// SetTotalServiceKeysNil sets the value for TotalServiceKeys to be an explicit nil
func (o *SpaceQuotaUpdateServices) SetTotalServiceKeysNil() {
	o.TotalServiceKeys.Set(nil)
}

// UnsetTotalServiceKeys ensures that no value is present for TotalServiceKeys, not even an explicit nil
func (o *SpaceQuotaUpdateServices) UnsetTotalServiceKeys() {
	o.TotalServiceKeys.Unset()
}

func (o SpaceQuotaUpdateServices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceQuotaUpdateServices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PaidServicesAllowed) {
		toSerialize["paid_services_allowed"] = o.PaidServicesAllowed
	}
	if o.TotalServiceInstances.IsSet() {
		toSerialize["total_service_instances"] = o.TotalServiceInstances.Get()
	}
	if o.TotalServiceKeys.IsSet() {
		toSerialize["total_service_keys"] = o.TotalServiceKeys.Get()
	}
	return toSerialize, nil
}

type NullableSpaceQuotaUpdateServices struct {
	value *SpaceQuotaUpdateServices
	isSet bool
}

func (v NullableSpaceQuotaUpdateServices) Get() *SpaceQuotaUpdateServices {
	return v.value
}

func (v *NullableSpaceQuotaUpdateServices) Set(val *SpaceQuotaUpdateServices) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceQuotaUpdateServices) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceQuotaUpdateServices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceQuotaUpdateServices(val *SpaceQuotaUpdateServices) *NullableSpaceQuotaUpdateServices {
	return &NullableSpaceQuotaUpdateServices{value: val, isSet: true}
}

func (v NullableSpaceQuotaUpdateServices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceQuotaUpdateServices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


