/*
Cloud Foundry API

OpenAPI specification for the Cloud Foundry API.

API version: 3.195.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpaceQuotaRelationshipsSpaces type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceQuotaRelationshipsSpaces{}

// SpaceQuotaRelationshipsSpaces struct for SpaceQuotaRelationshipsSpaces
type SpaceQuotaRelationshipsSpaces struct {
	// Spaces this quota is applied to
	Data []CreateAppRequestRelationshipsSpaceData `json:"data"`
}

type _SpaceQuotaRelationshipsSpaces SpaceQuotaRelationshipsSpaces

// NewSpaceQuotaRelationshipsSpaces instantiates a new SpaceQuotaRelationshipsSpaces object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceQuotaRelationshipsSpaces(data []CreateAppRequestRelationshipsSpaceData) *SpaceQuotaRelationshipsSpaces {
	this := SpaceQuotaRelationshipsSpaces{}
	this.Data = data
	return &this
}

// NewSpaceQuotaRelationshipsSpacesWithDefaults instantiates a new SpaceQuotaRelationshipsSpaces object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceQuotaRelationshipsSpacesWithDefaults() *SpaceQuotaRelationshipsSpaces {
	this := SpaceQuotaRelationshipsSpaces{}
	return &this
}

// GetData returns the Data field value
func (o *SpaceQuotaRelationshipsSpaces) GetData() []CreateAppRequestRelationshipsSpaceData {
	if o == nil {
		var ret []CreateAppRequestRelationshipsSpaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SpaceQuotaRelationshipsSpaces) GetDataOk() ([]CreateAppRequestRelationshipsSpaceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SpaceQuotaRelationshipsSpaces) SetData(v []CreateAppRequestRelationshipsSpaceData) {
	o.Data = v
}

func (o SpaceQuotaRelationshipsSpaces) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceQuotaRelationshipsSpaces) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SpaceQuotaRelationshipsSpaces) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpaceQuotaRelationshipsSpaces := _SpaceQuotaRelationshipsSpaces{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpaceQuotaRelationshipsSpaces)

	if err != nil {
		return err
	}

	*o = SpaceQuotaRelationshipsSpaces(varSpaceQuotaRelationshipsSpaces)

	return err
}

type NullableSpaceQuotaRelationshipsSpaces struct {
	value *SpaceQuotaRelationshipsSpaces
	isSet bool
}

func (v NullableSpaceQuotaRelationshipsSpaces) Get() *SpaceQuotaRelationshipsSpaces {
	return v.value
}

func (v *NullableSpaceQuotaRelationshipsSpaces) Set(val *SpaceQuotaRelationshipsSpaces) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceQuotaRelationshipsSpaces) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceQuotaRelationshipsSpaces) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceQuotaRelationshipsSpaces(val *SpaceQuotaRelationshipsSpaces) *NullableSpaceQuotaRelationshipsSpaces {
	return &NullableSpaceQuotaRelationshipsSpaces{value: val, isSet: true}
}

func (v NullableSpaceQuotaRelationshipsSpaces) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceQuotaRelationshipsSpaces) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


