/*
Cloud Controller API

API specification for managing environment variable groups in Cloud Controller.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capiclient

import (
	"encoding/json"
	"time"
)

// checks if the V3AppsGuidActionsRestartPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3AppsGuidActionsRestartPost200Response{}

// V3AppsGuidActionsRestartPost200Response struct for V3AppsGuidActionsRestartPost200Response
type V3AppsGuidActionsRestartPost200Response struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Guid *string `json:"guid,omitempty"`
	Lifecycle *V3AppsGuidActionsRestartPost200ResponseLifecycle `json:"lifecycle,omitempty"`
	Links *map[string]Get200ResponseLinksLogCache `json:"links,omitempty"`
	Name *string `json:"name,omitempty"`
	Relationships *V3AppsGuidActionsRestartPost200ResponseRelationships `json:"relationships,omitempty"`
	State *string `json:"state,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewV3AppsGuidActionsRestartPost200Response instantiates a new V3AppsGuidActionsRestartPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3AppsGuidActionsRestartPost200Response() *V3AppsGuidActionsRestartPost200Response {
	this := V3AppsGuidActionsRestartPost200Response{}
	return &this
}

// NewV3AppsGuidActionsRestartPost200ResponseWithDefaults instantiates a new V3AppsGuidActionsRestartPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3AppsGuidActionsRestartPost200ResponseWithDefaults() *V3AppsGuidActionsRestartPost200Response {
	this := V3AppsGuidActionsRestartPost200Response{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *V3AppsGuidActionsRestartPost200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *V3AppsGuidActionsRestartPost200Response) SetGuid(v string) {
	o.Guid = &v
}

// GetLifecycle returns the Lifecycle field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetLifecycle() V3AppsGuidActionsRestartPost200ResponseLifecycle {
	if o == nil || IsNil(o.Lifecycle) {
		var ret V3AppsGuidActionsRestartPost200ResponseLifecycle
		return ret
	}
	return *o.Lifecycle
}

// GetLifecycleOk returns a tuple with the Lifecycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetLifecycleOk() (*V3AppsGuidActionsRestartPost200ResponseLifecycle, bool) {
	if o == nil || IsNil(o.Lifecycle) {
		return nil, false
	}
	return o.Lifecycle, true
}

// HasLifecycle returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasLifecycle() bool {
	if o != nil && !IsNil(o.Lifecycle) {
		return true
	}

	return false
}

// SetLifecycle gets a reference to the given V3AppsGuidActionsRestartPost200ResponseLifecycle and assigns it to the Lifecycle field.
func (o *V3AppsGuidActionsRestartPost200Response) SetLifecycle(v V3AppsGuidActionsRestartPost200ResponseLifecycle) {
	o.Lifecycle = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetLinks() map[string]Get200ResponseLinksLogCache {
	if o == nil || IsNil(o.Links) {
		var ret map[string]Get200ResponseLinksLogCache
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetLinksOk() (*map[string]Get200ResponseLinksLogCache, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]Get200ResponseLinksLogCache and assigns it to the Links field.
func (o *V3AppsGuidActionsRestartPost200Response) SetLinks(v map[string]Get200ResponseLinksLogCache) {
	o.Links = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V3AppsGuidActionsRestartPost200Response) SetName(v string) {
	o.Name = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetRelationships() V3AppsGuidActionsRestartPost200ResponseRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret V3AppsGuidActionsRestartPost200ResponseRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetRelationshipsOk() (*V3AppsGuidActionsRestartPost200ResponseRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given V3AppsGuidActionsRestartPost200ResponseRelationships and assigns it to the Relationships field.
func (o *V3AppsGuidActionsRestartPost200Response) SetRelationships(v V3AppsGuidActionsRestartPost200ResponseRelationships) {
	o.Relationships = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *V3AppsGuidActionsRestartPost200Response) SetState(v string) {
	o.State = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *V3AppsGuidActionsRestartPost200Response) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3AppsGuidActionsRestartPost200Response) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *V3AppsGuidActionsRestartPost200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *V3AppsGuidActionsRestartPost200Response) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o V3AppsGuidActionsRestartPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3AppsGuidActionsRestartPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Lifecycle) {
		toSerialize["lifecycle"] = o.Lifecycle
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableV3AppsGuidActionsRestartPost200Response struct {
	value *V3AppsGuidActionsRestartPost200Response
	isSet bool
}

func (v NullableV3AppsGuidActionsRestartPost200Response) Get() *V3AppsGuidActionsRestartPost200Response {
	return v.value
}

func (v *NullableV3AppsGuidActionsRestartPost200Response) Set(val *V3AppsGuidActionsRestartPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV3AppsGuidActionsRestartPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV3AppsGuidActionsRestartPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3AppsGuidActionsRestartPost200Response(val *V3AppsGuidActionsRestartPost200Response) *NullableV3AppsGuidActionsRestartPost200Response {
	return &NullableV3AppsGuidActionsRestartPost200Response{value: val, isSet: true}
}

func (v NullableV3AppsGuidActionsRestartPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3AppsGuidActionsRestartPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


